apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: task-management-hub-backend
  title: Management task
  description: Backend application of task management
  annotations: 
    backstage.io/source-location: url:https://github.com/shefaliguptasg/team_task_mangement_hub/tree/feature/backstage/task_management_hub/server
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: task-management-hub-team
  system: task-management-hub-system
  providesApis:
    - task-management-hub-api
